name: Merge & deploy to production

on:
  workflow_dispatch:
    inputs:
      payload:
        description: Pages CMS payload as JSON
        required: true
        type: string

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Merge branch to master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH=$(echo '${{ github.event.inputs.payload }}' | jq -r '.repository.ref')
          git config user.name "zenix-cms"
          git config user.email "cms@zenix.app"
          git fetch origin "$BRANCH"

          PR_URL=$(gh pr list --head "$BRANCH" --json url --jq '.[0].url')
          if [ -n "$PR_URL" ]; then
            gh pr merge "$PR_URL" --merge --subject "Merge $BRANCH to master"
          else
            git merge --no-ff "$BRANCH" -m "Merge $BRANCH to master"
            git push origin master
          fi
